In [2]:
#Siyuan Li
#last update: 2024/2/1


import pandas as pd
import os

In [3]:
df = pd.read_csv("/data/Clockbase/Methylation/sample_disease.txt",sep=" ", header=0)  
result_df = pd.DataFrame()
#filter samples with disease label
selected_columns = df.columns[df.iloc[0].notna()]
result_df = pd.concat([result_df, df[selected_columns]], axis=1)

result_df.head()

/tmp/ipykernel_26805/4173742459.py:1: DtypeWarning: Columns (4,5,7,12,25,26,30,33,35,39,40,49,51,55,74,86,94,100) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/data/Clockbase/Methylation/sample_disease.txt",sep=" ", header=0)

,sample_id,age,braak_stage,disease,project_id,sex,tissue,sample_type,platform
GSM1068826,GSM1068826,88.0,6.0,Alzheimer's disease,GSE43414,F,brain - cerebellum,disease tissue,450K
GSM1068827,GSM1068827,92.0,3.0,Alzheimer's disease,GSE43414,F,brain - cerebellum,disease tissue,450K
GSM1068829,GSM1068829,93.0,6.0,Alzheimer's disease,GSE43414,F,brain - cerebellum,disease tissue,450K
GSM1068832,GSM1068832,96.0,5.0,Alzheimer's disease,GSE43414,F,brain - cerebellum,disease tissue,450K
GSM1068833,GSM1068833,86.0,6.0,Alzheimer's disease,GSE43414,M,brain - cerebellum,disease tissue,450K

In [4]:
print(result_df['disease'].unique())
print(result_df['platform'].unique())

["Alzheimer's disease" nan 'asthma' 'autism spectrum disorder'
 'childhood asthma' "Crohn's disease" "crohn's disease" 'Down syndrome'
 "Graves' disease" "Huntington's disease"
 'intellectual disability and congenital anomalies' 'Kabuki syndrome'
 'multiple sclerosis' 'nephrogenic rest' 'panic disorder'
 "Parkinson's disease" 'preeclampsia' 'psoriasis' 'respiratory allergy'
 'rheumatoid arthritis' 'schizophrenia' 'Silver Russell syndrome'
 "Sjogren's syndrome" 'spina bifida' 'stroke'
 'systemic insulin resistance' 'systemic lupus erythematosus'
 'systemic sclerosis' 'type 2 diabetes' 'Ulcerative colitis'
 'ulcerative colitis']
['450K']

In [5]:
num_rows = result_df.shape[0]
print("数据框有", num_rows, "行。")

数据框有 14501 行。

In [6]:
nan_rows = result_df[result_df['disease'].isna()]
num_nan_rows = nan_rows.shape[0]
print(" 'disease' 列中有", num_nan_rows, "行的值是 NaN。")

 'disease' 列中有 9188 行的值是 NaN。

In [7]:
result_df = result_df.dropna(subset=['disease'])
print(result_df['disease'].unique())
num_rows = result_df.shape[0]
print("数据框有", num_rows, "行。")

["Alzheimer's disease" 'asthma' 'autism spectrum disorder'
 'childhood asthma' "Crohn's disease" "crohn's disease" 'Down syndrome'
 "Graves' disease" "Huntington's disease"
 'intellectual disability and congenital anomalies' 'Kabuki syndrome'
 'multiple sclerosis' 'nephrogenic rest' 'panic disorder'
 "Parkinson's disease" 'preeclampsia' 'psoriasis' 'respiratory allergy'
 'rheumatoid arthritis' 'schizophrenia' 'Silver Russell syndrome'
 "Sjogren's syndrome" 'spina bifida' 'stroke'
 'systemic insulin resistance' 'systemic lupus erythematosus'
 'systemic sclerosis' 'type 2 diabetes' 'Ulcerative colitis'
 'ulcerative colitis']
数据框有 5313 行。

In [8]:
result_df.head()

,sample_id,age,braak_stage,disease,project_id,sex,tissue,sample_type,platform
GSM1068826,GSM1068826,88.0,6.0,Alzheimer's disease,GSE43414,F,brain - cerebellum,disease tissue,450K
GSM1068827,GSM1068827,92.0,3.0,Alzheimer's disease,GSE43414,F,brain - cerebellum,disease tissue,450K
GSM1068829,GSM1068829,93.0,6.0,Alzheimer's disease,GSE43414,F,brain - cerebellum,disease tissue,450K
GSM1068832,GSM1068832,96.0,5.0,Alzheimer's disease,GSE43414,F,brain - cerebellum,disease tissue,450K
GSM1068833,GSM1068833,86.0,6.0,Alzheimer's disease,GSE43414,M,brain - cerebellum,disease tissue,450K

In [9]:
df2 = pd.read_csv("/data/Clockbase/Methylation/disease/GSE43414.csv.gz",compression='gzip')  
df2.head()

,sample_id,GSM1068826,GSM1068827,GSM1068829,GSM1068832,GSM1068833,GSM1068834,GSM1068835,GSM1068838,GSM1068839,...,GSM1069260,GSM1069356,GSM1068908,GSM1069114,GSM1068860,GSM1069365,GSM1069253,GSM1069292,GSM1069238,GSM1069295
0,disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sample_type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,cg00050873,NaN,NaN,NaN,NaN,0.819,0.757,0.806,NaN,0.814,...,NaN,0.833,NaN,0.763,0.796,0.806,NaN,NaN,NaN,0.858
3,cg00212031,NaN,NaN,NaN,NaN,0.009,0.011,0.000,NaN,0.026,...,NaN,0.018,NaN,0.027,0.014,0.012,NaN,NaN,NaN,0.019
4,cg00213748,NaN,NaN,NaN,NaN,NaN,NaN,0.738,NaN,0.840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df2t=df2.transpose()
df2t.head()

,0,1,2,3,4,5,6,7,8,9,...,485504,485505,485506,485507,485508,485509,485510,485511,485512,485513
sample_id,disease,sample_type,cg00050873,cg00212031,cg00213748,cg00214611,cg00455876,cg01707559,cg02004872,cg02011394,...,ch.22.740407F,ch.22.757911F,ch.22.772318F,ch.22.43177094F,ch.22.44116734F,ch.22.909671F,ch.22.46830341F,ch.22.1008279F,ch.22.47579720R,ch.22.48274842R
GSM1068826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.166,0.034,NaN,0.333,NaN,NaN,0.889,0.026,0.32,0.165
GSM1068827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.162,NaN,NaN,0.266,NaN,NaN,0.894,0.039,0.373,0.148
GSM1068829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.116,0.058,NaN,0.271,NaN,NaN,0.926,0.083,0.279,0.098
GSM1068832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.198,NaN,NaN,...,0.099,0.098,NaN,0.373,NaN,NaN,0.918,0.111,0.197,0.266

In [11]:
print(df2t.index)

Index(['sample_id', 'GSM1068826', 'GSM1068827', 'GSM1068829', 'GSM1068832',
       'GSM1068833', 'GSM1068834', 'GSM1068835', 'GSM1068838', 'GSM1068839',
       ...
       'GSM1069260', 'GSM1069356', 'GSM1068908', 'GSM1069114', 'GSM1068860',
       'GSM1069365', 'GSM1069253', 'GSM1069292', 'GSM1069238', 'GSM1069295'],
      dtype='object', length=477)

In [12]:
#prepare a dataframe
data = pd.DataFrame(index=result_df['sample_id'])
data['disease'] = result_df['disease']
data['age'] = result_df['age']
data['sex'] = result_df['sex']
display(data)

                        disease   age sex
sample_id
GSM1068826  Alzheimer's disease  88.0   F
GSM1068827  Alzheimer's disease  92.0   F
GSM1068829  Alzheimer's disease  93.0   F
GSM1068832  Alzheimer's disease  96.0   F
GSM1068833  Alzheimer's disease  86.0   M
...                         ...   ...  ..
GSM2337520   ulcerative colitis  26.0   F
GSM2337609   ulcerative colitis  37.0   M
GSM2337524   Ulcerative colitis  34.0   M
GSM2337501   Ulcerative colitis  34.0   F
GSM2337391   ulcerative colitis  22.0   M

[5313 rows x 3 columns]

In [13]:

# get CpGs data
# set path
folder_path = "/data/Clockbase/Methylation/disease/"

# find path
file_names = os.listdir(folder_path)

# find GSE files
for file_name in file_names:
    if file_name.startswith("GSE"):  
        file_path = os.path.join(folder_path, file_name)
        # load CpGs data
        dfCpGs = pd.read_csv(file_path,compression='gzip')   
        dfCpGs_trans=dfCpGs.transpose()
        # map CpGs to profile
        data = data.join(dfCpGs_trans.iloc[:, 2:], how='left')

ValueError: columns overlap but no suffix specified: Index([     2,      3,      4,      5,      6,      7,      8,      9,     10,
           11,
       ...
       485504, 485505, 485506, 485507, 485508, 485509, 485510, 485511, 485512,
       485513],
      dtype='object', length=485512)

In [14]:
output_path="/data/Clockbase/Methylation/disease_predictor/"
if not os.path.exists(output_path):
    os.makedirs(output_path)
data.to_csv(os.path.join(output_path, 'dataraw.csv'),header=0, float_format='%.4f', index=True)